FROM python:3

# Copy the client.py file from the local src folder to the container
COPY src/client.py /usr/src/Client/

# Set working directory
WORKDIR /usr/src/Client

# Set ENTRYPOINT to call Python
ENTRYPOINT ["python3", "client.py"]